version: '3'

services:
    mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./mysql_data:/var/lib/mysql
        network_mode: "host"
    spring:
        build:
            context: ./spring
            dockerfile: Dockerfile
        image: "{SERVICES_SPRING_IMAGE_NAME}"
        restart: always
        network_mode: "host"
        depends_on:
            - mysql
    zookeeper:
        build:
            context: ./zookeeper
            dockerfile: Dockerfile
        ports:
            - "{DOCKER_ZOOKEEPER_PORT}:{DOCKER_ZOOKEEPER_PORT}"
    kafka:
        build:
            context: ./kafka
            dockerfile: Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "{DOCKER_KAFKA_PORT}:{DOCKER_KAFKA_PORT}"
        depends_on:
            - zookeeper