version: '3.1'
services:
    spring:
        build:
            context: ./spring
            dockerfile: Dockerfile
        image: {SERVICES_SPRING_IMAGE_NAME}
        restart: always
        ports:
            - {APPLICATION_PORT}:{APPLICATION_PORT}
    mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        ports:
            - {MYSQL_PORT}:3306
        volumes:
            - ./mysql_data:/var/lib/mysql
