server:
  port: {MY_APPLICATION_PORT}

spring:
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  application:
    name: user-service
  profiles:
    active: {SPRING_PROFILE_ACTIVE}
  config:
    import: configserver:http://{BACKEND_CONFIG_SERVER_IP}:{BACKEND_CONFIG_SERVER_PORT}